platform: x64

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.5
  CGO_LDFLAGS: "-static-libstdc++ -static-libgcc --disable-shared --enable-static -static -LC:/LLVM/lib -Wl,-Bstatic C:/LLVM/lib/libclang.lib"
# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

clone_folder: c:\gopath\src\cpp-codegen

install:
  - set PATH=%GOPATH%\bin;c:\go\bin;;%PATH%
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go1.5.windows-amd64.msi
  - msiexec /i go1.5.windows-amd64.msi /q
  - appveyor DownloadFile https://nuwen.net/files/mingw/history/mingw-14.0.exe
  - mingw-14.0.exe -oC:\mingw-cpp-codegen -y
  - c:\mingw-cpp-codegen\mingw\set_distro_paths.bat
  - powershell Start-Process "\"C:\Program Files\\LLVM\Uninstall.exe\"" -ArgumentList "/S" -Wait
  - mkdir c:\projects
  - cd c:\projects
  - git clone -b release_37 --depth 1 http://llvm.org/git/llvm.git
  - cd c:\projects\llvm\tools
  - git clone -b release_37 --depth 1 http://llvm.org/git/clang.git
  - cd c:\projects\llvm
  - mkdir _build
  - cd _build
  - cmake .. -G "Visual Studio 14 2015 Win64" -DCMAKE_RELEASE_TYPE=Debug -DCMAKE_INSTALL_PREFIX=C:\LLVM -DLLVM_TARGETS_TO_BUILD=X86 -DBUILD_SHARED_LIBS=Off
  - cmake --build . --target install --config Release
  - copy C:\LLVM\lib\libclang.lib c:\LLVM\lib\clang.lib
  - del C:\LLVM\bin\libclang.dll
  - go version
  - go env

build_script:
  - go get --ldflags "-extldflags \"-static-libstdc++ -static-libgcc --disable-shared --enable-static -static -LC:/LLVM/lib -Wl,-Bstatic C:/LLVM/lib/libclang.lib\"" -v -x ./...
  - go build --ldflags "-extldflags \"-static-libstdc++ -static-libgcc --disable-shared --enable-static -static -LC:/LLVM/lib -Wl,-Bstatic C:/LLVM\lib/libclang.lib\""  -v -x ./...
  - go test -c -o cpp-codegen-test.exe --ldflags "-extldflags \"-static-libstdc++ -static-libgcc --disable-shared --enable-static -static -LC:/LLVM/lib -Wl,-Bstatic C:/LLVM\lib/libclang.lib\"" -v -x ./...

artifacts:
  - path: cpp-codegen.exe
  - path: cpp-codegen-test.exe
